# Generated by Django 3.2.7 on 2021-10-27 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20211026_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_code',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
