# Generated by Django 3.2.7 on 2021-10-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_product_discount_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_code',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(default=0),
        ),
    ]
