# Generated by Django 3.2.7 on 2021-10-28 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_product_discount_code'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponProducy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('active_date_start', models.DateTimeField(blank=True, null=True)),
                ('active_date_end', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('product', models.ManyToManyField(to='services.Product')),
            ],
        ),
    ]
