# Generated by Django 3.2.7 on 2021-10-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_product_discount_code'),
        ('orders', '0003_couponproducy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CouponProducy',
            new_name='CouponProduct',
        ),
    ]
