# Generated by Django 3.2.7 on 2021-10-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_couponproducy_couponproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CouponProduct',
        ),
    ]
