# Generated by Django 3.2.7 on 2021-11-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20211107_0359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
