# Generated by Django 3.2.7 on 2021-11-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20211028_0111'),
        ('orders', '0007_delete_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='order_products', to='services.Product'),
        ),
    ]
